---
- name: user module demo
  tasks:
    - name: user example present
      ansible.builtin.user:
        name: vra
        password: "Netapp01$"
        groups:
          - wheel
          - adm
        state: "present"
        shell: "/bin/bash"
        system: false
        create_home: true
        home: "/home/example"
        comment: "Ansible example"
        generate_ssh_key: true
